services:
  content-managemant-api:
    image: content-management-api:latest
    ports:
      - 3000:3000
    environment:
      APP_PORT: 3000
      MONGO_USER: root
      MONGO_PASSWORD: password
      MONGO_HOST: mongo
      MONGO_PORT: 27017