name: 'Slack Nodify'
description: 'Notify to Slack'
inputs:
  json-payload:  
    description: 'Slack Json Attachments'
    required: true
    default: '{\"channel\": \"C0254UUPR0E\", "attachments": [  {\"text\":\"Hello, there!!! I am SLEEPY HOLLOW!!!\"} ] }'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: |
        curl -XPOST -H "Authorization: Bearer ${{ env.SLACK_BOT_TOKEN }}" -H "Content-Type: application/json" \
        "https://slack.com/api/chat.postMessage"  \
        -d ${{ inputs.json-payload }}
      shell: bash