name: gauge-test
on: [push]
jobs:
  post-actions-triged-message:
    runs-on: ubuntu-20.04
    steps:
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.14.0
      with:
        channel-id: 'C0254UUPR0E'
        slack-message: 'The action is executed!!!'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  e2e-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - run: curl -SsL https://downloads.gauge.org/stable | sh -s -- --location-[custom path]
    - run: gauge install java --version 0.7.15
    - run: mvn test
      working-directory: ./e2e
  content-management-api-unit-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.5'
    - run: make test
      working-directory: ./content-management-api
