name: sleepy-hollow-actions
on: 
  pull_request:
    branches:
      - main
jobs:
  post-actions-triged-message:
    runs-on: ubuntu-20.04
    steps:
    - name: Post actions trigerd message
      id: slack
      uses: slackapi/slack-github-action@v1.14.0
      with:
        channel-id: 'C0254UUPR0E'
        slack-message: 'The actions are executed by ${{ github.actor }}’s PR!!!'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  e2e-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - run: curl -SsL https://downloads.gauge.org/stable | sh -s -- --location-[custom path]
    - run: gauge install java --version 0.7.15
    - run: make test
      working-directory: ./e2e
    - uses: ./.github/actions/slack-notify-action
      with:
        channel-id: 'C0254UUPR0E'
        attachmments: '[ {\"color\": \"#2eb67d\", \"text\":\"E2E Test Passed!!! GOOD JOB!!!\"} ]'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      if: ${{ success() }}
    - uses: ./.github/actions/slack-notify-action
      with:
        channel-id: 'C0254UUPR0E'
        attachmments: '[  {\"color\": \"#E01E5A\", \"text\":\"E2E Test Faliled!!! FIX IT NOW!!!\"} ]'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      if: ${{ failure() }}
  content-management-api-unit-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.5'
    - run: make test
      working-directory: ./content-management-api
    - uses: ./.github/actions/slack-notify-action
      with:
        channel-id: 'C0254UUPR0E'
        attachmments: '[ {\"color\": \"#2eb67d\", \"text\":\"Content Management Api Unit test passed!!! GOOD JOB!!!\"} ]'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      if: ${{ success() }}
    - uses: ./.github/actions/slack-notify-action
      with:
        channel-id: 'C0254UUPR0E'
        attachmments: '[  {\"color\": \"#E01E5A\", \"text\":\"Content Management API Unit Test Faliled!!! FIX IT NOW!!!\"} ]'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      if: ${{ failure() }}
  # merge-branch-dev-to-main:
  #   needs: [e2e-test, content-management-api-unit-test]
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Merge development -> main
  #     uses: devmasx/merge-branch@v1.3.1
  #     with:
  #       type: now
  #       target_branch: ${{ github.base_ref }}
  #       github_token: ${{ github.token }}
  #   - name: Post Merge message 
  #     id: slack
  #     uses: slackapi/slack-github-action@v1.14.0
  #     with:
  #       channel-id: 'C0254UUPR0E'
  #       slack-message: 'All test passed!!! Merged ${{ github.head_ref }} to ${{ github.base_ref }}!!! GREAT JOB!!!'
  #     env:
  #       SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
