name: execute tests
on: 
  pull_request:
    branches:
      - main
jobs:
  post-actions-triged-message:
    runs-on: ubuntu-20.04
    steps:
    - name: Post actions trigerd message
      id: slack
      uses: slackapi/slack-github-action@v1.15.0
      with:
        channel-id: 'C0254UUPR0E'
        slack-message: 'The actions are executed by ${{ github.actor }}’s PR!!!'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  e2e-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - run: curl -SsL https://downloads.gauge.org/stable | sh -s -- --location-[custom path]
    - run: gauge install java --version 0.7.15
    - run: make compose-up
      working-directory: ./content-management-api
    - run: make test
      working-directory: ./e2e
    - uses: ./.github/actions/slack-notify-action
      with:
        json-payload: '{"channel": "C0254UUPR0E", "attachments": [  {"color": "#2EB67D", "text": "E2E Test Passed!!! GOOD JOB!!!"} ] }'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      if: ${{ success() }}
    - uses: ./.github/actions/slack-notify-action
      with:
        json-payload: '{"channel": "C0254UUPR0E", "attachments": [  {"color": "#E01E5A", "text": "E2E Test Faliled!!! FIX IT NOW!!!"} ] }'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      if: ${{ failure() }}
  content-management-api-unit-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17.1'
    - run: make test
      working-directory: ./content-management-api
    - uses: ./.github/actions/slack-notify-action
      with:
        channel-id: 'C0254UUPR0E'
        json-payload: '{"channel": "C0254UUPR0E", "attachments": [  {"color": "#2EB67D", "text": "Content Management API Unit Test Passed!!! GOOD JOB!!!"} ] }'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      if: ${{ success() }}
    - uses: ./.github/actions/slack-notify-action
      with:
        json-payload: '{"channel": "C0254UUPR0E", "attachments": [  {"color": "#E01E5A", "text": "Content Management API Unit Test Faliled!!! FIX IT NOW!!!"} ] }'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      if: ${{ failure() }}
